let kiraStore={catalog:{voices:[],ai:[],plugins:[]},installed:{}};
async function loadCatalog(){try{const r=await fetch('/catalog',{cache:'no-store'});if(!r.ok)throw Error(await r.text());kiraStore=await r.json();renderStore('voices','voiceCatalogList');renderStore('ai','aiCatalogList');renderStore('plugins','pluginCatalogList')}catch(e){console.error('Kira Store',e)}}
function meta(x){return [x.size_mb?'≈ '+x.size_mb+' MB':'',x.ram_gb?'RAM '+x.ram_gb+' GB':'',x.speed?'⚡ '+x.speed:'',x.quality?'✦ '+x.quality:'',x.style||'',x.category||''].filter(Boolean).map(v=>'<span>'+v+'</span>').join('')}
function renderStore(kind,target){const el=document.getElementById(target);if(!el)return;let items=kiraStore.catalog[kind]||[];if(kind==='voices')items=items.filter(x=>x.gender==='female');const st=kiraStore.installed||{};el.innerHTML=items.map(x=>{const yes=(st[kind]||[]).includes(x.id);const active=kind==='voices'?String(st.active_voice||'').includes(x.id):st.active_ai===x.id;return '<div class="catalogItem" data-search="'+(x.name+' '+(x.note||'')+' '+(x.category||'')).toLowerCase()+'"><h3>'+x.name+'</h3><small>'+(x.lang||x.note||x.kind||'')+'</small><div class="catalog-meta">'+meta(x)+'</div><div class="actions">'+(kind==='voices'?'<button onclick="previewVoice(\''+x.id+'\')">▶ Послушать</button>':'')+(yes?'<button '+(active?'disabled':'')+' onclick="useCatalog(\''+kind+'\',\''+x.id+'\')">'+(active?'★ Используется':'Использовать')+'</button><button onclick="removeCatalog(\''+kind+'\',\''+x.id+'\')">🗑</button>':'<button onclick="installCatalog(\''+kind+'\',\''+x.id+'\',this)">⬇ Установить</button>')+'</div></div>'}).join('')}
function storeSearch(inp,target){const q=inp.value.trim().toLowerCase();document.querySelectorAll('#'+target+' .catalogItem').forEach(c=>c.style.display=(c.dataset.search||'').includes(q)?'':'none')}
async function installCatalog(kind,id,b){b.disabled=true;b.textContent='⏳ Установка…';const box=b.closest('.catalogItem'),bar=document.createElement('div');bar.className='store-progress';bar.innerHTML='<i></i>';box.appendChild(bar);let n=5;const t=setInterval(()=>{n=Math.min(90,n+5);bar.firstChild.style.width=n+'%'},400);try{const r=await fetch('/catalog/'+kind+'/'+encodeURIComponent(id)+'/install',{method:'POST'});if(!r.ok)throw Error(await r.text());clearInterval(t);bar.firstChild.style.width='100%';setTimeout(loadCatalog,250)}catch(e){clearInterval(t);bar.remove();b.disabled=false;b.textContent='↻ Повторить'}}
function previewVoice(id){new Audio('/catalog/voices/'+encodeURIComponent(id)+'/preview?t='+Date.now()).play().catch(console.error)}
async function useCatalog(kind,id){const r=await fetch('/catalog/'+kind+'/'+encodeURIComponent(id)+'/use',{method:'POST'});if(r.ok)loadCatalog()}
async function removeCatalog(kind,id){if(!confirm('Удалить '+id+'?'))return;const r=await fetch('/catalog/'+kind+'/'+encodeURIComponent(id),{method:'DELETE'});if(r.ok)loadCatalog()}
window.addEventListener('load',loadCatalog);

function enhanceKiraStore(){
 [['voiceCatalog','voices','voiceCatalogList','голосов'],['aiCatalog','ai','aiCatalogList','моделей'],['pluginCatalog','plugins','pluginCatalogList','плагинов']].forEach(d=>{
  const root=document.getElementById(d[0]);if(!root||root.querySelector('.kira-store-toolbar'))return;
  const bar=document.createElement('div');bar.className='kira-store-toolbar';
  const all=document.createElement('button'),mine=document.createElement('button'),search=document.createElement('input'),count=document.createElement('span');
  all.textContent='Все';all.className='active';mine.textContent='Установленные';search.placeholder='🔎 Поиск…';count.className='store-count';
  const apply=mode=>{const q=search.value.trim().toLowerCase(),st=kiraStore.installed||{};document.querySelectorAll('#'+d[2]+' .catalogItem').forEach(c=>{const id=c.getAttribute('data-id')||'',okMode=mode==='all'||(st[d[1]]||[]).includes(id),okSearch=!q||c.innerText.toLowerCase().includes(q);c.style.display=okMode&&okSearch?'':'none'});all.classList.toggle('active',mode==='all');mine.classList.toggle('active',mode==='installed')};
  all.onclick=()=>apply('all');mine.onclick=()=>apply('installed');search.oninput=()=>apply(all.classList.contains('active')?'all':'installed');count.textContent=((kiraStore.installed||{})[d[1]]||[]).length+' '+d[3]+' установлено';
  bar.append(all,mine,search,count);root.insertBefore(bar,document.getElementById(d[2]));
 });
}
const kiraStoreLoadBase=loadCatalog;
loadCatalog=async function(){await kiraStoreLoadBase();document.querySelectorAll('.kira-store-toolbar').forEach(x=>x.remove());document.querySelectorAll('.catalogItem').forEach(c=>{const title=c.querySelector('h3');if(title){const groups=kiraStore.catalog||{};for(const kind of ['voices','ai','plugins']){const item=(groups[kind]||[]).find(i=>i.name===title.textContent);if(item){c.setAttribute('data-id',item.id);break}}}});enhanceKiraStore()}
